Add deploy job

diff --git a/.forgejo/workflows/build_nixos_configs.yml b/.forgejo/workflows/build_nixos_configs.yml
--- a/.forgejo/workflows/build_nixos_configs.yml
+++ b/.forgejo/workflows/build_nixos_configs.yml
@@ -1,13 +1,20 @@
-name: Build NixOS Configurations
+name: Build and Deploy NixOS Configurations
 on: [push]
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    continue-on-error: true
     container:
       image: node:25
       volumes:
         - "/nix:/nix"
+    outputs:
+      carbon_success: ${{ steps.set-output.outputs.carbon_success }}
+      framework_success: ${{ steps.set-output.outputs.framework_success }}
+      git_success: ${{ steps.set-output.outputs.git_success }}
+      gospel_success: ${{ steps.set-output.outputs.gospel_success }}
+      node_success: ${{ steps.set-output.outputs.node_success }}
     strategy:
       matrix:
         system:
@@ -19,13 +26,55 @@ jobs:
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
-      - run: |
+
+      - name: Build configuration
+        run: |
           echo 'Building configuration for ${{ matrix.system }}'
           nix --extra-experimental-features nix-command --extra-experimental-features flakes \
             build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
+
       - name: Push build to attic
         run: |
           nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#attic-client \
             -- login gospel https://attic.kilonull.com ${{ secrets.ATTIC_PUSH_SECRET }}
           nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#attic-client \
             -- push --ignore-upstream-cache-filter gospel:nixosConfigs ./result
+
+      - name: Set success output
+        id: set-output
+        run: echo "${{ matrix.system }}_success=true" >> "$FORGEJO_OUTPUT"
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    container:
+      image: node:25
+      volumes:
+        - "/nix:/nix"
+    strategy:
+      matrix:
+        system:
+          - "git"
+    steps:
+      - name: Check build status
+        run: |
+          if [ "${{ needs.build.outputs[format('{0}_success', matrix.system)] }}" != "true" ]; then
+            echo "Build for ${{ matrix.system }} did not succeed, failing deploy"
+            exit 1
+          fi
+          echo "Build for ${{ matrix.system }} succeeded, proceeding with deploy"
+
+      - name: Check out repository code
+        uses: actions/checkout@v4
+
+      - name: Setup deploy key
+        env:
+          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
+        run: |
+          mkdir -p ~/.ssh
+          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
+
+      - name: Deploy ${{ matrix.system }}
+        run: |
+          nix --extra-experimental-features 'nix-command flakes' develop --impure --command \
+            deploy .#${{ matrix.system }}
